### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by xgqt** [yanyingwang/colorize#3]
Please add a license file as well as the license field to the `info.rkt` file, for example: `(define license 'MIT)`

**Comment by yanyingwang** [comment]
https://github.com/yanyingwang/colorize/commit/918a3509a3fd314f0dc90876545a55ebf753022a

**Comment by xgqt** [comment]
Thanks a lot for quick action but the value used for `license` for single license packages should be a single symbol, not a list, so `'Apache-2.0` instead of `'(Apache-2.0)` in this case.

Docs: https://docs.racket-lang.org/pkg/metadata.html#%28tech._license._s._expression%29
Sorry for not linking this in earlier :)
